apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-zap
  labels:
    app: zap
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: zap
  template:
    metadata:
      labels:
        app: zap
    spec:
      containers:
      - name: zap
        image: {{ .Values.zap.image.repository }}:{{ .Values.zap.image.tag }}
        ports:
        - containerPort: {{ .Values.zap.port }}
