apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-zap-service 
spec:
  selector:
    app: zap  
  ports:
    - protocol: TCP
      port: {{ .Values.zap.port }}
      targetPort: {{ .Values.zap.port }}
  type: ClusterIP  # Accessible only within the cluster
