apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "1800"
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
  selector:
    app: {{ .Release.Name }}
