apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: backend-sa-rolebinding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: backend-sa
    namespace: default
roleRef:
  kind: Role
  name: backend-sa-role
  apiGroup: rbac.authorization.k8s.io
