apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: 619071345478.dkr.ecr.us-west-2.amazonaws.com/aest/backend:latest
        env:
        - name: ZAP_BASE_URL
          value: "http://zap-service:8080"  
        ports:
        - containerPort: 8000
      imagePullSecrets:
      - name: ecr-secret  # Created on EKS secret
