apiVersion: v1
kind: Service
metadata:
  name: zap-service
spec:
  selector:
    app: zap
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP  # Accessible within the cluster only
