replicaCount: 1
namespace: default  

image:
  repository: ${ECR_REPOSITORY}
  tag: latest
  pullPolicy: Always

imagePullSecret: ecr-secret

service:
  type: LoadBalancer

zapBaseUrl: "http://zap-service:8080"

s3:
  bucketName: ${S3_BUCKET_NAME}
  accessKey: ""
  region: ${AWS_REGION}

serviceAccount:
  name: backend-sa
  roleArn: ${SERVICE_ACCOUNT_ROLE_ARN}
